// Code generated by "stringer -type=tokenTyp"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tokenTypUnknown-0]
	_ = x[tokenTypIdent-1]
	_ = x[tokenTypInt-2]
	_ = x[tokenTypLParen-3]
	_ = x[tokenTypRParen-4]
	_ = x[tokenTypComma-5]
	_ = x[tokenTypString-6]
	_ = x[tokenTypSemicolon-7]
	_ = x[tokenTypEOF-8]
}

const _tokenTyp_name = "tokenTypUnknowntokenTypIdenttokenTypInttokenTypLParentokenTypRParentokenTypCommatokenTypStringtokenTypSemicolontokenTypEOF"

var _tokenTyp_index = [...]uint8{0, 15, 28, 39, 53, 67, 80, 94, 111, 122}

func (i tokenTyp) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_tokenTyp_index)-1 {
		return "tokenTyp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenTyp_name[_tokenTyp_index[idx]:_tokenTyp_index[idx+1]]
}
